version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgres_db
    hostname: postgres-host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview_transjakarta
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    hostname: mosquitto-host
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq-host
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    depends_on:
      - db
      - rabbitmq
      - mqtt
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: ["/bin/app"]
    volumes:
      - .:/app
    networks:
      - app-network
    restart: always


volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
